# Solution Combinatorics with Voiceovers
*Arthur Ryman, last updated 2025-06-19*

[<img src="images/colab-badge.png" alt="Open in Colab" style="width: 15%;">
](https://colab.research.google.com/github/agryman/instant-insanity/blob/main/notebooks/Solution-Combinatorics-Voiceovers.ipynb)

## Introduction

This notebook focuses on the combinatorics of the Instant Insanity puzzle, namely how to count the number of combinations of the cubes.
Other notebooks will focus on other aspects of the puzzle such as its graph theory solution and history.

This notebook contains both voiceovers and explanatory text.
The voiceovers are intended for use in the video.
The explanatory text goes into more detail but may be too detailed for use in video.

## Change History

This is a working document and will be edited frequency.
I will annotate each voiceover with the date of its most recent update.

### 2025-05-17

Added start times for the YouTube videos as per 
[Issue 23](https://github.com/agryman/instant-insanity/issues/23):
* Robin Wilson https://www.youtube.com/watch?v=sI7lX3M7OZo&t=46s
* Tai-Danae Bradley https://www.youtube.com/watch?v=Lw1pF47N-0Q&t=65s

### 2025-06-19

Moved the discussion of the Cube Colour Table out of the Graph Theory notebook and into this notebook.

## Combinatorics

This section should come after the general introduction to the puzzle.
We should have already described the puzzle and defined what it means to solve it, namely you are required to line up the four cubes in a horizontal row such that
no colour is repeated along the front, back, top, or bottom sides.

This notebook shows how to compute the total number of combinations of the Instant Insanity puzzle.
The branch of mathematics that focuses on how to count combinations is called *Combinatorics*.
The number of combinations for any puzzle is very interesting since it indicates how hard it is to solve the
puzzle.

## Scene: How Difficult is This Puzzle?

The purpose of this scene is to give the viewer a feel for the difficulty of the puzzle.

Show an animation that hints at the difficulty of searching for a solution.
Show the row of four cubes. 
Pick one cube at random and give it a random rotation, then check if we have a solution.
Maybe show a big red X and a buzzer sound like in game shows.
Keep repeating this process to show that simply trying random arrangements would be very unlikely to succeed.

### Voiceover: last updated 2025-04-15

How difficult is it to solve the puzzle?
One way to solve it is to try every possible combination of the cubes until we find one that works.
In computer science, this solution strategy is called a brute-force search.
In the absence of any further insight into how to solve the puzzle,
its difficulty is therefore directly proportional to the total number of combinations.

So how many combinations are there?

## Scene: 82,944 or 41,472?

The purpose of this scene is to introduce the minor controversy about conflicting claims for the number of combinations.

Show the text "82,944 or 41,472?"

### Voiceover: last updated 2025-04-16

Here we encounter an interesting situation. 
We have two competing claims for the number of combinations.
The puzzle package, and several YouTube videos, claim that there are 82,944 combinations.
However, an paper published at Cambridge University in 1947 by Carteblanche gives an elegant solution to the puzzle and claims that there are only 41,472.

## Scene: Winning Solutions: 82,944

See: [Instant Insanity](https://winning-moves.com/product/InstantInsanity.asp)

The purpose of this scene is to establish that the puzzle package claims there are 82,944 combinations.

Show the puzzle package and the text: "82,944 Combinations. Can You Solve It?"

<div style="text-align: center;">
    <img src="images/package-front.jpeg" alt="Instant Insanity package" style="width: 25%;">
</div>

### Voiceover: lasted updated 2025-04-04

The 2024 Winning Solutions Instant Insanity package advertises 82,944 combinations.

###### Scene: Robin Wilson, Gresham College: 82,944

See: [The Four Cubes Problem](https://youtu.be/sI7lX3M7OZo?si=ijtOwtu-WV1sY4lH)

The purpose of this scene is to establish that the Robin Wilson video claims there are 82,944 combinations.

Play a clip from the YouTube video where Robin Wilson says there are 82,944 combinations.

Starting at 0:46 https://youtu.be/sI7lX3M7OZo?t=46, he says:

> I've only got five minutes left. Unfortunately, there are 82,944 ways of stacking them and only one way works.

He then shows a diagram at the 1:01 mark which contains the statement:

> 82944 ways - only one works.

End the clip after 1:01 mark showing the diagram for a few seconds.

### Voiceover: last updated 2025-04-11

The 2008 Gresham College lecture, The Four Cubes Problem
by Robin Wilson, Gresham Professor of Geometry, gives the number as 82,944.


## Scene: Tai-Danae Bradley, PBS Infinite Series: 82,944

See: [Instant Insanity Puzzle](https://youtu.be/Lw1pF47N-0Q?si=WX3NlcEhPNLdY6Na)

The purpose of this scene is to establish that the Tai-Danae Bradley video claims there are 82,944 combinations.

Play a clip from the YouTube video where Tai-Danae Bradley video says there are 82,944 combinations.

At 1:05 https://youtu.be/Lw1pF47N-0Q?t=65 she says:

> All right, there are thousands of different configurations that we can make with these cubes, 82,944
> to be exact, which is why this is often called the Instant Insanity puzzle.

End the clip at 1:17 showing the frame that displays the word: 82,944 configurations Instant Insanity Puzzle

### Voiceover: last updated 2025-04-15

The 2018 PBS Infinite Series video, Instant Insanity Puzzle  by Tai-Danae Bradley
also gives the number as 82,944.

## Scene: F. de Carteblanche, Eureka: 41,472

See: [The Coloured Cubes Problem
](https://onedrive.live.com/?authkey=%21AG4HZAmpHD0fSWs&cid=BF134020839BC69B&id=BF134020839BC69B%21210&parId=BF134020839BC69B%21147&o=OneUp)

The purpose of this scene is to establish that the 1947 Carteblanche paper claims there are 41,472 combinations.

Show the statement from the 1947 Carteblanche paper.

<div style="text-align: center;">
    <img src="images/the-chance-is-1-in-41472.png" alt="The Chance is 1 in 41472" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-04

The 1947 Eureka paper, The Coloured Cubes Problem
by F. de Carteblanche which gives the elegant graph theory solution to the problem states that if you pick a random arrangement
of the cubes your chance of it being a solution is 1 in 41,472.
At that time, the puzzle was called the Tantalizer.
F. de Carteblanche was the pseudonym of a group of four Cambridge mathematics students which included the future eminent graph theorist
Bill Tutte.

## Scene: Which Number is Correct?

The purpose of this scene is to present the conflicting claims side-by-side.

Show the puzzle box (82,944) and the 1947 Carteblanche paper (41,472) side-by-side, highlighting the two numbers.

### Voiceover: last updated 2025-04-15

Neither the original 1947 Carteblanche paper nor the YouTube videos actually show us how they arrived at their numbers.
Let's apply some combinatorics and compute the answer ourselves.

## Scene: Naming the Cubes and Their Faces

The purpose of this scene is to assign names to the cubes and their faces so we can talk about them more easily.
We'll use these names to describe how the cubes are coloured and organize this information into a table.
We'll use the naming scheme on p9 of the 1947 Carteblanche paper.

<div style="text-align: center;">
    <img src="images/face-colour-table.png" alt="Face Colour Table" style="width: 25%;">
</div>

Start by showing a horizontal row of the four cubes.
The perspective should be chosen so that the front, right, and top faces are visible.

Fade in the numbers from 1 to 4 to name the cubes.

Fade in the names x, y, and z on the front, right, and top faces of each cube.

Animate unfolding the cubes and add the names x', y', and z' to the back, left, and bottom faces.

Animate rearranging the faces of each flattened cube into a vertical column of six faces in the order x, x', y, y', z, z'.

Animate moving the faces into an array with six rows (one per face) and four columns (one per cube).

Fade in the table row and column names to produce a table like that on p9 of Carteblache but using the actual layout of the cubes in the current Winning Moves puzzle.
Here is the table for the puzzle.

| Face | 1 | 2 | 3 | 4 |
|------|---|---|---|---|
| x (front)   | G | R | W | B |
| x' (back)   | W | G | R | R |
| y (right)   | B | B | W | G |
| y' (left)   | R | B | B | W |
| z (top)     | R | W | G | B |
| z' (bottom) | R | G | R | W |

When the voiceover mentions face 3y', highlight its row and column showing the B entry.

### Voiceover: last updated 2025-04-16

TO DO: Quote a line from the 1947 paper where Carteblanche discusses the introduction of symbolic names.

The task of describing and counting the number of combinations will be easier if we assign short symbolic names to the cubes and their faces.

We'll use the naming scheme defined on page 9 of the 1947 Carteblanche paper.

First pick some arbitrary order for the cubes and name them 1, 2, 3, and 4.

Next pick some arbitrary orientation for each cube and name the front, right, and top faces x, y, and z.
Name their opposite faces x', y', and z'.

We'll use the colours from the Winning Moves puzzle rather than the original Tantalizer colours.
Abbreviate red as R, green as G, blue as B, and white as W.

Organize the face colour information into a table with six rows (one for each face) and 4 columns (one for each cube).
We'll refer to this table as the face colour table.

For example, face 3y' is the name of the left face of cube 3.
It's colour is given in the cell at row y' and column 3 of the face colour table.
We can look up the colour of this face in the table and see that it is B which stands for blue.

## Scene: The Face Colour Table

The purpose of this scene is to explain how Carteblanche labelled the cube faces and 
summarized their colours in a table.

TO DO: Merge this cell with the preceding one.

Show the following table which contains the face colours of the cubes in Instant Insanity using the layout
from Carteblanche's 1947 paper.

<div style="text-align: center;">
    <img src="images/latex/instant-insanity-table.png" alt="Instant Insanity Face Colours" style="width: 75%;">
</div>

For bonus marks show an animation where we start with the four cubes and the table with no colours filled in.
Then one at a time, label the faces of the cubes, unfold them, and move their faces into the table.

In [1]:
!cat voiceovers/combinatorics/the-face-colour-table.txt

Here is a table that summarizes the face colours for Instant Insanity
using the notatlabelling scheme given in Carteblanche's paper.

We have numbered the cubes from 1 to 4.
Of course, there is nothing special about this particular numbering.
There are 4 factorial, namely 24, ways to number the cubes and we have arbitrarily picked one of them.

We have also labelled each face as 
x for front,
x prime for back,
y for right,
y prime for left,
z for top, and
z prime for back.

A face labelled with primed letter is opposite the face labelled with that unprimed letter.

The letters correspond to the usual x-y-z axes of three-dimensional space oriented using the so-called right-hand rule.
If you grab the z-axis with your right hand pointing your thumb in the position z direction then
your finger point in the direction of a rotation that sends the x-axis towards the y-axis.

There are also 24 ways to label the faces of a cube.
This comes about by first labelling any one of the six faces of th

## Scene: Combination and Solutions

The purpose of this scene is to precisely define the terms combination and solution, and to settle on using a horizontal row when displaying combinations, rather than a vertical stack.

Show a vertical stack solution and the sentence from the 1947 Carteblache paper that says:

> The problem is to stack these cubes in a vertical pile (thus forming a square prism) in such a way that each of the four vertical faces of this pile contains all four colours.

Show a horizontal row solution and the sentence from the back of the puzzle box that says:

> Can you arrange the cubes in a row or stack so that all four colors appear on each side?

Maybe split the screen into left and right frames and show a vertical stack on the left and a horizontal row on the right, with the textual quotes below them.

### Voiceover: last updated 2025-04-15

First we need to precisely define what we mean by a combination of the cubes and a solution of the puzzle.
The 1947 Carteblanche paper describes the goal of the puzzle as follows:

The problem is to stack these cubes in a vertical pile (thus forming a square prism) in such a way that each of the four vertical faces of this pile contains all four colours.

The Winning Moves puzzle box asks:

Can you arrange the cubes in a row or stack so that all four colors appear on each side?

We'll call any vertical or horizontal arrangement of the four cubes a combination and any combination that solves the puzzle a solution.

Clearly, we'll get the same number of combinations whether we arrange the cubes vertically or horizontally since we can easily convert one type of arrangement into the other.
In this video, we'll usually arrange the cubes in a horizonal row.

## Scene: The Probability of a Solution

Show the following mathematical formula (images/latex/solution-probability.png):

<div style="text-align: center;">
    <img src="images/latex/solution-probability.png" alt="Solution Probability" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-14

Carteblanche makes the following claim.

The chance of obtaining the solution by a random arrangement of the cubes is only 1 in 41,472.

Let N be the total number of possible cube combinations and let S be the total number of solutions.
Let P be the probability that a randomly chosen combination is a solution.
The probability P is therefore the number of solutions S divided by the number of combinations N.

Let's compute N and S and see what we get for P.

## Scene: Generating all Possible Combinations

The purpose of this scene is to show what it means to generate a random combination.

Animate a random cube combination generator.
This could be like one of those lottery machines that scrambles numbered balls and pumps them out one at a time to produce the winning number.
Alternatively, it could be a physics simulation of dropping the four cubes and then lining them up in a horizontal row.

### Voiceover: last updated 2025-04-14

To generate all possible combinations, consider the following random procedure.
Put the four cubes in a bag, shake it, draw the cubes out one at a time, and, without looking at them, arrange them in a row.
If we repeat this procedure often enough it will eventually produce all possible combinations.

How many combinations can we produce?

Observe that we can fully describe any combination by first giving the order of the cubes,
and then giving the orientation of each cube.

## Scene: Naming Combinations

The purpose of this scene is to explain how we can use the cube and face naming scheme to name combinations

Show the row of cubes defined by the four-tuple (3y'z, 1xy, 4x'z, 2zx).
Include all the visible face names.

### Voiceover: 2025-04-16

We can use the cube and face names that we just defined to create a name any combination.
Imagine that each face of each cube is labelled with its name.
For example, the faces of cube 3 are labelled 3x, 3y, 3z, 3x', 3y', and 3z'.

Now select some cube, say cube 3, and orient it so that its y' is on top and its z face is in front.
Name that orientation y'z. Adding the cube number we get the name 3y'z.

Now take any horizontal row of the four cubes and list the names of their orientations from left to right as a four-tuple,
for example (3y'z, 1xy, 4x'z, 2zx).

## Scene: Counting the Number of Cube Orderings

The purpose of this scene is to count the number of cube orderings.

A nice way to visualize this is to create a horizontally oriented tree.

Put the root node on the left. It represents and empty sequence of cubes.

We need to pick the first cube in the order.
There are four choices so draw 4 arcs from the root to each of the choices.
We could draw the cube with its name or just the name.

Next we choose the second cube.
There are now only three possible choices so draw three arcs from the first cube to each of the three possible second cubes.

Proceed until all four cubes have been chosen.
The final tree has 24 leaf nodes.

Animate counting the leaf nodes by writing the numbers 1 to 24 to the right of each root node.

### Voiceover: last updated 2025-04-14

We're now ready to count the total number of possible cube orderings.
We'll build up each ordering from left to right and keep track of our progress in a decision tree.
Each cube ordering requires us to make four choices.
We have four choices for the first cube.
After we have made the first choice there are three cubes left so for each choice of the first cube we have three possibilities left for the second cube.
Similarly, for each ordering of the first two cubes we have two possibilities left for the third cube.
Finally, for each ordering of the first three cubes we only have one possibility left for the four cube.

Count all the cube orderings. There are 24 of them.

## Scene: Factorials

The purpose of this scene is to make contact with the concept of permuations and the factorial function.

Show an image of the math formula for $n!$ (images/latex/n-factorial.png):

<div style="text-align: center;">
  <img src="images/latex/n-factorial.png" alt="n Factorial" style="width: 50%;">
</div>

Then fade that general formula into the case $n = 4$ giving the answer $24$ (images/latex/4-factorial.png):

<div style="text-align: center;">
  <img src="images/latex/4-factorial.png" alt="4 Factorial" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-14

Combinatorics is the branch of mathematics that tells us how to count things.

One of the most important cases in combinatorics is how to count the number of ways that you can arrange a set of distinct objects in some order.
An arrangement of a set of distinct objects in some order is called a permuation of that set.

Combinatorics tells us that there are n factorial permuations of a set of n distinct objects.
To see this, observe that there are n ways to pick the first object, then n minus 1 ways to pick the second, and so on.

This is exactly how we counted the number of cube orders.
There are four cubes and four factorial equals twenty-four.

## Scene: The factorial Function in Python

This is an optional scene.

The purpose of this scene is to show how Python supports combinatorics.
Show the following Jupyter notebook Python cells.

### Voiceover: last updated 2025-04-14

Python has some built-in support for combinatorics.

Let's compute four factorial

In [2]:
4 * 3 * 2 * 1


24

### Voiceover: last updated 2025-04-14

Python has a built-in factorial function.
Import it from the math package.

In [3]:
from math import factorial

number_of_cube_orderings = factorial(4)

print(number_of_cube_orderings)

24


## Scene: Counting the Number of Cube Orientations

The purpose of this scene is to count the number of cube orientations.
We'll build up each orientation by first choosing the top face and then choosing the front face.

Start with an animation showing a cube. 
Rotate the cube slowly about each axis so that we can see the face names x, y, z, x', y', and z'.

Next we'll build up a decision tree from left to right.
The leftmost node is the tree root which represents no choices yet.

We'll choose the top face first.
Draw six lines from the root to nodes that represent the six possible top faces x, y, z, x', y', and z'.

Then draw four lines from each of the six possible top face nodes to four more nodes that represent the possible front faces.

The following table summarizes the possible choices for the front face given a choice for the top face.
| Top | Front |
|-----|-------|
| x | y, z, y', z' |
| x' | y, z, y', z' |
| y | x, z, x', z' |
| y' | x, z, x', z' |
| z | x, y, x', y' |
| z | x, y, x', y' |

Finally, count the number of the leaf nodes.
There are 24. Draw each cube to the right of the corresponding leaf node.

Here is a table of the orientations.

| Number | Top | Front |
|--------|-----|-------|
| 1 | x | y |
| 2 | x | z |
| 3 | x | y' |
| 4 | x | z' |
| 5 | x' | y |
| 6 | x' | z |
| 7 | x' | y' |
| 8 | x' | z' |
| 9 | y | x |
| 10 | y | z |
| 11 | y | x' |
| 12 | y | z' |
| 13 | y' | x |
| 14 | y' | z |
| 15 | y' | x' |
| 16 | y' | z |
| 17 | z | x |
| 18 | z | y |
| 19 | z | x' |
| 20 | z | y' |
| 21 | z' | x |
| 22 | z' | y |
| 23 | z' | x' |
| 24 | z' | y' |

### Voiceover: last updated 2025-04-14

How many ways can a single cube be oriented?
We can specify an orientation by saying which face is on top and which face is in front.
Let's count the number of orientations.

We'll use another basic theorem of combinatorics. 
If we have two sets of things, say A containing n things and B containing m things
then the number of ways we can pair things from A with things from B is n times m.

A cube has 6 faces. Therefore, there are 6 ways to pick the top face.

Having picked the top face, we can pick any of the four adjacent faces as the front face by spinning the cube about its vertical axis.
We can do this in four ways.

Therefore, the total number of cube orientations is six times four which equals twenty-four.

## Optional Python Code

In [4]:
number_of_top_face_choices = 6

number_of_front_face_choices = 4

number_of_cube_orientations = number_of_top_face_choices * number_of_front_face_choices

print(number_of_cube_orientations)

24


## Scene: Counting the Number of Combinations

The purpose of this scene is to compute the total number of combinations $N$.
We'll use the previously computed values for the number of cube orderings and orientations.

Show an image of the following math formula (images/latex/n-equals-7962624.png):

<div style="text-align: center;">
  <img src="images/latex/n-equals-7962624.png" alt="N equals 7,962,624" style="width: 50%;">
</div>


### Voiceover: last updated 2025-04-16

A combination is fully specified by giving the ordering of the four cubes and the orientation of each of cube.
There are 24 orderings of the cubes.
Each cube has 24 orientations.
Apply the basic combination rule again to get the total number of combinations.
Multiply the number of cube orderings and the number of cube orientations multiplied by itself four times
which is the same as raising the number of cube orientations to the power 4.

We get a whopping total of 7,962,624 combinations which is much bigger than the number of combinations, namely 82,944, claimed on the box and in the YouTube videos.
Why the difference?

The answer to this question is that, although there really are 7,962,624 distinct cube combinations that can be obtained through random draws, 
we can group the combinations into a much smaller collection of families whose members are related to each other through what are known as symmetry operations. 
Furthermore, all of the solutions belong to a single family.
Therefore, we can speed up our search for a solution by only checking one member of each family.

Group theory is the branch of mathematics that tells us about symmetry operations.
Sets of related symmetry operations form transformation groups.
Members of the set that are transformed into eachother by the group are called orbits of the group.
Our improved search strategy is then to check just one member of each orbit.

## Optional Python Code

In [5]:
N = number_of_combinations = number_of_cube_orderings * number_of_cube_orientations ** 4

print(N)

7962624


## Scene: When Are Two Combinations Essentially Equivalent?

The purpose of this scene is to introduce the notion of essentially equivalent combinations by first considering the cube ordering.

Line up the four cubes in a solution.
The following combination is a solution:

$$
(1zx', 2zx', 3zy', 4zx')
$$

Animate the action of swapping the positions of any two cubes and noting that we still have a solution.
Do a few swaps, e.g. swap cubes 1 and 2, 2 and 4, etc.
If we started with a solution then we still have a solution after the swaps.

### Voiceover: last updated 2025-04-14

We can specify a combination by giving a cube ordering and an orientation for each cube.
An orientation is given by specifying the top and front faces.
Consider the combination given by the four-tuple (one z x', two z x', three z y', four z x').
This combination is in fact a solution.

Now create a new combination by swapping the positions of any two cubes, say one and two, without changing their orientations.
The new combination is given by the four-tuple (two z x', one z x', three z y', four z x').
Since each side of the row contained four different colours before the swap, it will still contain four different colours after the swap.
Therefore the new combination is also a solution.

In general, changing the order of the cubes while perserving the orientation of each cube sends combinations to combinations and solutions to solutions.
We can achieve any cube ordering by swapping pairs of cubes.
As we computed above, there are twenty-four possible orderings of four cubes.
Therefore, we can use swaps to split up the set of all combinations into families that each consist of twenty-four related combinations.
This means that given any solution, it belongs to a family of twenty-four solutions that differ from each other only in the cube ordering.

It is natural to regard solutions that differ only in the cube ordering as being essentially equivalent since we can transform one into the other by a sequence of swaps.
We can therefore use this notion of equivalence to cut down the size of our search space by a factor of twenty-four.
Rather than examining all combinations for solutions, we can safely confine our attention to one fixed cube ordering, say the natural ordering one, two, three, four.

## Scene: The Number of Combinations Modulo Order

The purpose of this scene is to compute the number of combinations that are essentially distinct when we disregard cube orderings.

Display an image of the following mathematical formulas (images/latex/n-mod-o-equals-331776.png):

<div style="text-align: center;">
  <img src="images/latex/n-mod-o-equals-331776.png" alt="N mod O equals 331,776" style="width: 50%;">
</div>

### Voiceover

Let O = 24 denote the number of combinations that differ only in cube ordering.
This is the size of the orbits of the swap operations.

As previously discussed, we are going to regard all combinations that differ only in cube ordering as being essentially equivalent.
When mathematicians say that two objects are equivalent with regard to some property, they say that the objects are equivalent modulo that property, more briefly, mod that property.
Let's calculate the number of combinations modulo ordering.
Since the swap operations divide the set of all combinations into orbits of size 24,
the number of combinations modulo ordering is the number of combinations divided by 24.

Now we get that there are 331,776 essentially distinct combinations which is much smaller than 7,962,624 but still much bigger than 82,944.
Why are we still getting more than 82,944?
The reason is that we should regard more combinations as being essentially equivalent.
We'll do this next.

## Optional Python Code

In [6]:
size_O = 24
number_of_combinations_O = number_of_combinations // size_O

number_of_combinations_O

331776

## Scene: Quarter Turns About the Horizontal Axis

The purpose of this scene is to describe the symmetry operation that consists of rotation the row one quarter of a turn about the horizontal axis.

Show an animation of rotating the combination one-quarter turn about the horizontal axis.
Use the solution and point out that this operation results in another solution.

### Voiceover: last updated 2025-04-16

Suppose we start with a solution. 
Then we can easily generate another solution simply by rotating the combination one quarter of a turn about the horizontal axis.

For example, observe that the top side contains four different colours.
After rotation what was the top side is now the front side so it contains four different colours.
Then same observation applies to all four sides so this operation sends solutions to solutions.

We can perform this quarter turn rotation four times before ending up with the combination we started with.
Therefore each solution belongs of a family of four essentially equivalent solutions.

## Scene: The Number of Combinations Modulo Order and Quarter Turns

The purpose of this scene is to compute the number of essentially distinct combinations when we additionally regard combinations that
differ by a quarter turn along the horizontal axis as being equivalent.

Display an image of the following mathematical formulas (images/latex/n-mod-oq-equals-82944.png):

<div style="text-align: center;">
  <img src="images/latex/n-mod-oq-equals-82944.png" alt="N mod OQ equals 82944" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-16

A quarter turn about the horizontal axis does not change the cube ordering.
Therefore this additional symmetry operation increases the size of our families of essentially equivalent combinations by a factor of four and 
so reduces the number of combinations we need to check by the same factor.

Let Q be the set of these quarter-turn symmetry operations. Clearly, this operation does not change the order the cubes
and so it sends one O orbit to another. 
In fact, it groups the set the O orbits into sets of four related orbits.
We refer to these combined orbits as OQ orbits.
Each OQ orbit contains 4 times 24 = 96 combinations.

Let's compute the number of OQ orbits.
Take the number of combinations modulo O, namely 331,776, and divide it by the size of the Q orbit, namely 4,
to get 82,944 of the number of combinations module OQ.

Progress! Now we understand where the number 82,944 comes from.
It is the number of essentially distinct combinations where we consider combinations related by operations O or Q to be essentially equivalent.

But what about 41,472?
The explanation is similar to the above.
We have yet another symmetry operation.

This additional symmetry operation is similar to the quarter turns but is a little less obvious.
If you like challenges, pause the video and see if you can visualize this additional symmetry operation.

## Optional Python Code

In [7]:
size_Q = 4
number_of_combinations_OQ = number_of_combinations_O // size_Q

print(number_of_combinations_OQ)

82944


## Scene: Half Twists About the Vertical Axis

The purpose of this scene is to describe the symmetry operation that consists of rotation of each cube one half of a turn about its vertical axis.

Show an animation of rotating each cube one-half turn about its vertical axis.
Use the solution and point out that this operation results in another solution.

### Voiceover: last updated 2025-04-16

Suppose we have a combination. 
We can obtain another combination by rotating each cube by one half turn about its vertical axis.
We'll call this operation a half twist to distinguish it from a quarter turn.

A half twist does not change the cube ordering.
It also leaves the top and botton faces unchanged.
A half twist simply interchanges the front and back faces of the combination.
It also interchanges the left and right faces of each cube but they do not contribute to the solution so we can ignore them.

Suppose we started with a solution.
Since the top and bottom sides are unchanged, they each contain four different colours before and after the operation.
The back and front sides also each contain four distinct colours before the operation.
But the operation simply interchanges the back and front so they still each contain four different colours after the operation.
Therefore the half twist operation sends solutions to solutions.

## Scene: The Number of Combinations Modulo Order, Quarter Turns, and Half Twists

The purpose of this scene is to compute the number of essentially distinct combinations when we additionally regard combinations that
differ by a half twist along the vertical axis as being equivalent.

Display an image of the following mathematical formulas (images/latex/n-mod-oqh-equals-41472.png):

<div style="text-align: center;">
  <img src="images/latex/n-mod-oqh-equals-41472.png" alt="N mod OQH equals 41472" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-16

Let H be the set of half twist operations. 
The cube orientation produced by a half twist is always different from any cube orientation that can be produced by applying some sequence of quarter turns to the starting orientation.
We can apply a half twist twice before returning to the starting orientation.
The orbit generated by H has size 2.
Therefore, we need to further divide the number of combinations by 2 to get the number of essentially distinct combinations when we regard combinations that differ by a half twist to
be essentially equivalent.

When we apply the H and Q operations, we get an orbit of size 2 times 4 = 8.
Applying the O operations to the QH orbits, we get an OQH orbit of size 8 times 24 = 192.
Therefore every combination belongs to a family of 192 essentially equivalent combinations.
So every solution belongs to family of 192 essentially equivalent solutions.

Let's compute the number of OQH orbits.
Divide the number of OQ orbits, namely 82,944, by the size of an H orbit, namely 2, to give the result 41,472.

Eureka! Carteblanche was right.
We now understand where the number 41,472 comes from. 
It is the number of essentially distinct combinations if we consider combinations that are related by O, Q, or H symmetry operations to be essentially equivalent.
Furthermore, as we will soon prove, there is exactly one essentially distinct combination that solves the problem.

In summary, there are around 8 million combinations but these are divided into orbits of symmetry operations each consisting of 192 mutually equivalent combinations.
The total number of essentially distinct combinations is 41,472 and this is the true meassure of the difficulty of finding a solution by simply checking all combinations.
However, we can find the solution much more easily by using the elegant graph theory approach discovered by Carteblanche.

## Optional Python Code

In [8]:
size_H = 2
number_of_combinations_OQH = number_of_combinations_OQ // size_H

print(number_of_combinations_OQH)

41472


In [9]:
S = size_O * size_Q * size_H

print(S)

192


In [10]:
print(N // S)

41472


## Scene: Brute-Force Search

The purpose of this scene is to estimate how long it would take a human to try all essentially distinct combinations.

Show an image of the following mathematical formulas (images/latex/brute-force-daily-rate.png):

<div style="text-align: center;">
  <img src="images/latex/brute-force-daily-rate.png" alt="Brute-force Daily Rate" style="width: 50%;">
</div>

Fade to an image of the following mathematical formulas (images/latex/brute-force-search.png)
after the voiceover says "our human could try 17,280 combinations per day":

<div style="text-align: center;">
  <img src="images/latex/brute-force-search.png" alt="Brute-force Search" style="width: 50%;">
</div>

### Voiceover: last updated 2025-04-25

We now know how many essentially distinct combinations, namely 41,472, we'd have to check in order to find a solution.
Given enough time and patience, we could systematically generate every possible essentially distinct combination
and check if it was a solution. 
Mathematicians call this approach a brute-force search.

How long would it take a human to perform a brute-force search?
Let's compute the total time.

As a rough estimate, suppose it takes our human 1 second to rotate a cube and 1 second to check
if the combination is a solution.
In some cases our human would have to rotate all four cubes to generate the next combination,
So allowing four seconds to rotate the cubes and 1 second to check the combination means it would take our human 5 seconds per combination.

There are 60 seconds in a minute, 60 minutes in an hour, and 24 hours in a day giving a total of 86,400 seconds per day.
At 5 seconds per combination, our human could try 17,280 combinations per day.

There are 41,472 essentially distinct combinations.
Therefore, our human would find the solution if they worked nonstop for 2.4 days and made no errors.
This is called the worst case time since it assumes that we are unlucky and have to generate all the combinations
before we find the solution.

This puzzle is clearly challenging, which likely contributes to its enduring popularity. 
According to the packaging from Winning Moves, over 20 million copies have been sold!

## Optional Python Code

In [11]:
seconds_per_combination = 5
total_seconds = number_of_combinations_OQH * seconds_per_combination

print(total_seconds)

207360


In [12]:
seconds_per_minute = 60
minutes_per_hour = 60
hours_per_day = 24
seconds_per_day = seconds_per_minute * minutes_per_hour * hours_per_day

print(seconds_per_day)

86400


In [13]:
total_days = total_seconds / seconds_per_day

print(total_days)

2.4


## Optional Python Brute-Force Search

How long would a computer take to find the solution? 
One of us actually tried this in 1967 using a Fortran 4 program running on their high school's IBM 1130 computer.
Next, we'll write some Python code to perform the brute-force search and then optimize it for speed.